# Generated by Django 3.0.3 on 2020-02-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20200226_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='description',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
