# Generated by Django 3.0.3 on 2020-02-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genAuth', '0002_userverificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverificationtoken',
            name='token',
            field=models.CharField(default='ee0408baf2ee8c72da45049b7a1d928d1466684a1b89519171be7b3ce565c5d3', editable=False, max_length=200, unique=True),
        ),
    ]
