# Generated by Django 3.0.3 on 2020-02-22 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genAuth', '0004_auto_20200222_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssocode',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='userverificationtoken',
            name='token',
            field=models.CharField(default='a6b1ea4867acaec70a3ab0a044249d359d97a8d07e11eb2d403cdc774b9a7aee', editable=False, max_length=200, unique=True),
        ),
    ]
