# Generated by Django 3.0.3 on 2020-02-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genAuth', '0006_auto_20200222_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverificationtoken',
            name='token',
            field=models.CharField(default='abe0e88ac9eae591f8b3a25326cff35af85801ab3c4847f212c851ac98142c17', editable=False, max_length=200, unique=True),
        ),
    ]
