# Generated by Django 3.0.3 on 2020-02-22 10:38

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('genAuth', '0007_auto_20200222_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverificationtoken',
            name='token',
            field=models.CharField(default=secrets.token_hex, editable=False, max_length=200, unique=True),
        ),
    ]
